logging:
  level: WARN
  loggers:
    org.trellisldp: INFO
    io.dropwizard: INFO

storage:
    - name: repository
      ldpnr: /Users/acoburn/trellisData/datastreams
      ldprs: /Users/acoburn/trellisData/objects
      url: http://localhost:8080/repository

namespaceFile: /Users/acoburn/trellisData/namespaces.json
ensemble: localhost:2181
bootstrapServers: localhost:9092
unsupportedTypes: [message/external-body]
