logging:
  level: WARN
  loggers:
    edu.amherst.acdc.trellis.app: INFO

dataPath: /Users/acoburn/trellisData
binaryPath: /Users/acoburn/trellisBinary
ensemble: localhost:2181
bootstrapServers: localhost:9092
