logging:
  level: WARN
  loggers:
    edu.amherst.acdc.trellis.app: INFO

ldprsDirectory: /Users/acoburn/trellisData/objects
ldpnrDirectory: /Users/acoburn/trellisData/datastreams
namespaceFile: /Users/acoburn/trellisData/namespaces.json

ensemble: localhost:2181
bootstrapServers: localhost:9092
