server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: WARN
  loggers:
    org.trellisldp: INFO
    io.dropwizard: INFO

partitions:
    - id: repository
      binaries:
          prefix: "file:repository/"
          path: /Users/acoburn/trellisData/binaries
          levels: 4
      resources:
          path: /Users/acoburn/trellisData/resources
      baseUrl: http://localhost:8080/

namespaceFile: /Users/acoburn/trellisData/namespaces.json

zookeeper:
    ensembleServers: localhost:2181

kafka:
    bootstrapServers: localhost:9092

enableWebAc: false
userPrefix: "user:"
enableBasicAuth: true
enableAnonAuth: true
basicAuthFile: users.auth
