server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: WARN
  loggers:
    org.trellisldp: INFO
    io.dropwizard: INFO

partitions:
    - id: repository
      binaries:
          path: /Users/acoburn/trellisData/binaries
      resources:
          path: /Users/acoburn/trellisData/resources
      baseUrl: http://localhost:8080/

namespaces:
    file: /Users/acoburn/trellisData/namespaces.json

zookeeper:
    ensembleServers: localhost:2181

kafka:
    bootstrapServers: localhost:9092

auth:
    webac:
        enabled: false
    anon:
        enabled: true
    basic:
        enabled: true
        usersFile: users.auth

cors:
    allowOrigin:
        - "*"
    maxAge: 180

