server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: WARN
  appenders:
    - type: file
      currentLogFilename: /tmp/trellis/log/trellis.log
      archive: true
      archivedLogFilePattern: /tmp/trellis/log/trellis-%d.log
      archivedFileCount: 5
      maxFileSize: 100K
  loggers:
    org.trellisldp: INFO
    io.dropwizard: INFO

partitions:
    - id: repository
      binaries:
          path: /tmp/trellis/binaries
      resources:
          path: /tmp/trellis/resources
      baseUrl: http://localhost:8080/

namespaces:
    file: /tmp/trellis/namespaces.json

zookeeper:
    ensembleServers: localhost:2181

kafka:
    bootstrapServers: localhost:9092

auth:
    webac:
        enabled: true
    anon:
        enabled: true
    jwt:
        enabled: true
        base64Encoded: false
        key: secret
    basic:
        enabled: true
        usersFile: users.auth

cors:
    allowOrigin:
        - "*"
    maxAge: 180

